### ISSUE TITLE
simple table crashes RTF export

### ISSUE THREAD

**Issue by NeomMob** [fletcher/MultiMarkdown-4#109]
a simple table 

| Header One     | Header Two     |
| :------------- | :------------- |
| Item One       | Item Two       |

crashes when exporting to RTF : pointer being freed was not allocated

**Comment by fletcher** [comment]
RTF support is provided "as is."  RTF is a crappy document format, which I have addressed ad nauseum over the years so won't repeat myself here.

I included some preliminary rtf code to encourage those who value it to contribute.  Thus far no one has taken up my offer in years of offering.  I encourage you to contribute patches to improve and extend RTF support.


Otherwise, if you really need RTF, the best approach is MMD->ODF->RTF (via Libre Office).

Alternatively you can look at whether pandoc's RTF support is sufficient for you.

My contributions for RTF will be limited to those times when I get bored or inexplicably motivated to work on it.  I currently have way too much other stuff going on for that to happen any time soon...  ;)

**Comment by NeomMob** [comment]
I couldn't agree more on the crappy side of RTF. I have however no alternative for my project. Thanks for your answer. I will try to find the issue and to fix it.

**Comment by fletcher** [comment]
Before you spend too much time, I would also be sure that the rest of your document will work properly.  RTF conversion is pretty limited, and tables are *very* limited.

I agree that your specific table should not cause an error, but many (most?) tables will not work properly.

I hate for you to fix one problem only to realize that this is fundamentally not the right tool for your needs.
