### ISSUE TITLE
Invalid XML/HTML with Markdown inside nested block element tags

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-4#122]
The following input ...
```markdown
</div markdown="1">
Text

Paragraph

Text
</div>
```
will lead to
```html
<div>
Text

<p>Paragraph</p>
Text
</div>
```
which is correct. Neither a problem with this input:
```markdown
<div markdown="1">
<div markdown="1">
Text

Paragraph

Text
</div>
</div>
```
```html
<div>
<div>
Text

<p>Paragraph</p>
Text
</div>
</div>
```
But this one produces an invalid nesting of tags:
```markdown
<div markdown="1">
<div markdown="1">
Text

Paragraph

Text
</div>

</div>
```
```html
<div>
<div>
Text

<p>Paragraph</p>

<p>Text
</div></p>
</div>
```
Maybe it's a corner case but it rather shouldn't produce invalid XML/HTML. I'd prefer a rule where everything inside an HTML block element is never influenced by anything outside this block element, but I have to admit that it's probably not easy to achieve.
One further observation, this input "corrects" the problem which seems to be a bit strange:
```
<div markdown="1">

<div markdown="1">
Text

Paragraph

Text
</div>

</div>
```

**Comment by fletcher** [comment]
Nothing inside an HTML block element is being influenced by anything outside.  The "unbalanced" whitespace inside your outermost `<div>` is causing the irregularities -- meaning that the innermost `<div>` is not a block, but rather two unrelated tags (to MMD) that look related to you (`<div>` and `</div>`).

The last example you show is the correct one, where the innermost `<div>` is actually a Markdown block element, which is why you get the output you expect.


I agree that MMD shouldn't produce invalid HTML, but if you give it "incorrect" HTML/MMD there's not much I can do about it.
