### ISSUE TITLE
Support for indexes

### ISSUE THREAD

**Issue by jakobjanot** [fletcher/MultiMarkdown-4#131]
Is it or could it be possible to mark keywords in the text, which will be referred to in an index. Such a feature would be nice for creating books.

**Comment by fletcher** [comment]
There is not currently a way to manage LaTeX indexes with MMD syntax.  I have thought about such an idea for many years, but haven't found a solution that I like short of manually tagging each word -- which is not a particularly useful solution, and would only work in LaTeX, since the other output formats don't support the concept of an index.  In that case you're just as well off using the actual LaTeX `\index{}` commands.

**Comment by jakobjanot** [comment]
Thanks for the answer.
I am using it for books which are published to print through XSL-FO, thus
any way of manually tagging words would suffice. I am a bit unsure, if the
"glossary" method would work?
Best wishes.
Jakob

2015-08-31 18:34 GMT+02:00 Fletcher T. Penney <notifications@github.com>:

**Comment by fletcher** [comment]
I don't use XSL-FO, so can't really help you work out a way to "hack" it.
